// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace IMGGameplayTags
{
	IMAGINEGAME_API FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);

	// Declare all the custom native tags that Act will use
	IMAGINEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_IsDead);
	IMAGINEGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cooldown);
	IMAGINEGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cost);
	IMAGINEGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsBlocked);
	IMAGINEGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsMissing);
	IMAGINEGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Networking);
	IMAGINEGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_ActivationGroup);
	
	IMAGINEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);
	
	IMAGINEGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	IMAGINEGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	IMAGINEGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	IMAGINEGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	
	IMAGINEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	IMAGINEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	IMAGINEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	IMAGINEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);
	
	IMAGINEGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	IMAGINEGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset);
	IMAGINEGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_RequestReset);
	
	IMAGINEGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	IMAGINEGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Heal);
	
	IMAGINEGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_GodMode);
	IMAGINEGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_UnlimitedHealth);

	IMAGINEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouching);
	IMAGINEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	IMAGINEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	IMAGINEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead)
	
	IMAGINEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking);
	IMAGINEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_NavWalking);
	IMAGINEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Falling);
	IMAGINEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Swimming);
	IMAGINEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Flying);

	IMAGINEGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Custom);
	
	// These are mappings from MovementMode enums to GameplayTags associated with those enums (below)
	IMAGINEGAME_API extern const TMap<uint8, FGameplayTag> MovementModeTagMap;
	IMAGINEGAME_API extern const TMap<uint8, FGameplayTag> CustomMovementModeTagMap;
}
